### ISSUE TITLE
combine taxon's with different attributes

### ISSUE THREAD

**Issue by sckott** [zachary-foster/taxa2#1]
@zachary-foster Changed over to using taxa2 - on branch `taxa-work` in taxize repo. 

I'm not quite sure how to address this, but here's the problem. 

For all taxize `get_*` fxns (e.g., `get_gbif`), there's an associated `as.*` fxn (e.g., `as.gbif`). The as.gbif is for coercing an ID to a object that is the same class as what we get form get_gbif. Ideally one could combine outputs of get_gbif and as.gbif, but doesn't seem possible with taxa2 as is, or at least with my code developed on top of taxa2. 

This works, combing outputs of get_gbif and get_gbif

```r
a <- get_gbif(sci='Puma concolor')
b <- get_gbif(sci='Homo sapiens')
a
#> <taxon[1]>
#> [1] 2435099|Puma concolor|species
#> Rank levels: species

b
#> <taxon[1]>
#> [1] 2436436|Homo sapiens|species
#> Rank levels: species

c(a, b)
#> <taxon[2]>
#> [1] 2435099|Puma concolor|species 2436436|Homo sapiens|species
#> Rank levels: species
```

but if I try to combine output of get_gbif and as.gbif it doesn't work, with a attributes error

```r
d <- as.gbif(2436436)
d
#> <taxon[1]>
#> [1] 2436436|NA

c(a, d)
#> Error: Can't combine `..1` <taxon> and `..2` <taxon>.
#> ✖ Some attributes are incompatible.
#> ℹ The author of the class should implement vctrs methods.
#> ℹ See <https://vctrs.r-lib.org/reference/faq-error-incompatible-attributes.html>.
#> Run `rlang::last_error()` to see where the error occurred.
```

- Here's where `taxa_taxon` is defined https://github.com/ropensci/taxize/blob/taxa-work/R/taxa_taxon.R - similar to `taxa2:::taxon` - used in `get_gbif`
- Here's where we use `taxa_taxon` https://github.com/ropensci/taxize/blob/taxa-work/R/zzz.R#L38-L46 within `as.gbif` function - where we don't have all the information we have when using a get_* function, so there's some NA's. 

Is it just the NA's that's causing the incompatible attributes error?

**Comment by zachary-foster** [comment]
Hi Scott, 

I submitted a PR in taxize to fix this. It looks like you need to specify how `txid` vectors can be combined with other things (including themselves, oddly). If you don't, then `vctrs` is super picky about what can be combined. You did this partly already, but the code was not exported. I had assumed that `vctrs` would fall back to the `taxa_taxon` functions, but I guess it does not in this case. 

I don't fully understand the details, but this seems useful:

https://vctrs.r-lib.org/reference/howto-faq-coercion.html

**Comment by sckott** [comment]
thanks, having a look at the PR
